#Andersen-devops lesson 2
#Getting the HelloWorld app from this repository, preparing and running it
#Require the configured sudo
---
- hosts: "deb10srv"

  tasks:
  #Prepare environment
  - name: "Install pip3 and setuptools"
    become: yes
    apt:
      name:
      - "python3-pip"
      - "python-setuptools"
      state: "latest"
      update_cache: true

  - name: "Install Flask"
    become: yes
    pip:
      name: "flask"
      executable: "pip3"

  #Prepare for obtaining and obtain sources
  - name: "Install git and SVN"
    become: yes
    apt:
      name:
      - "git"
      - "subversion"
      state: "latest"
      update_cache: true

  - name: "Get helloworld app"
    subversion:
      repo: https://github.com/NereySer/Andersen-devops/trunk/lesson%202/python/
      dest: ~/python/hlwd

  #Prepare and run daemon
  - name: "Copy daemon config"
    become: yes
    template:
      src: "~/python/hlwd/tools/hlwd.service.j2"
      dest: "/etc/systemd/system/hlwd.service"
    notify:
      - "systemctl reload"

  - name: "Flush handlers"
    meta: flush_handlers

  - name: "Run daemon"
    become: yes
    service:
      name="hlwd.service"
      state="started"
      enabled=yes

  handlers:
  - name: "systemctl reload"
    become: yes
    command: systemctl daemon-reload

  - name: "Restart daemon"
    become: yes
    service:
      name: "hlwd.service"
      state: "restarted"
      enabled: yes


...

